services:
  web:
    build:
      context: /home/dav/jiahaohlc/docker/caronte/
      dockerfile: ./dockerfiles/base/ubbasse 
      args: #Variables de DFILE para la construcci√≥n de las imagenes 
        - USUARIO=jiahao
    container_name: ${CONTAINER_NAME}
    image: dsegura97/ubbasse
    # environment:
    #   - USUARIO=jiahao
    #   - PASSWORD=1234
    ports:
      - ${PORT_SSH}:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netcaronte:
        ipv4_address: ${IP_WEB}
networks:
  netcaronte:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

