services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/ubbasse 
    container_name: ${CONTAINER_NAME}
    image: dsegura97/ubbasse
    ports:
      - ${PORT_SSH}:80
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netbase:
        ipv4_address: ${IP_WEB}
networks:
  netbase:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}